const app=document.getElementById('app');let state=null,session=JSON.parse(localStorage.getItem('glitch-session')||'null'),events=null,intro=0,muted=localStorage.getItem('glitch-muted')==='1',sort=[],tapTimes=[],prevPhase='',lastRender='',remaining=0;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=()=>`<header class="top"><div class="logo">GLI₮CH_</div><button class="pill" onclick="toggleMute()">${muted?'🔇 MUTED':'🔊 SOUND'}</button></header>`;
const btn=(text,fn,cls='')=>`<button class="btn ${cls}" onclick="${fn}">${text}</button>`;
function sound(){if(muted)return;try{let a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=480;g.gain.setValueAtTime(.06,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.09);o.start();o.stop(a.currentTime+.1)}catch{}}
function vibrate(){navigator.vibrate?.(25)}function toggleMute(){muted=!muted;localStorage.setItem('glitch-muted',muted?'1':'0');render()}
async function api(action,body={}){let r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,...body,action})});let j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function save(s){session=s;localStorage.setItem('glitch-session',JSON.stringify(s));connect()}
async function create(){try{let name=document.querySelector('#name').value.trim();if(!name)throw Error('Enter a name');save(await api('create',{name}))}catch(e){error(e.message)}}
async function join(){try{let name=document.querySelector('#name').value.trim(),code=document.querySelector('#code').value.toUpperCase().trim();if(!name||code.length!==4)throw Error('Enter your name and four-letter code');save(await api('join',{name,code}))}catch(e){error(e.message)}}
function error(t){let e=document.querySelector('.error');if(e)e.textContent=t;else alert(t)}
function connect(){events?.close();if(!session)return render();events=new EventSource('/events?id='+encodeURIComponent(session.id));events.onmessage=e=>{let next=JSON.parse(e.data),old=state?.phase;state=next;if(old&&old!==next.phase){sound();vibrate();sort=[];tapTimes=[]}render()};events.onerror=()=>{if(events?.readyState===2){session=null;state=null;localStorage.removeItem('glitch-session');render()}}}
function home(){return `${icon()}<div class="hero">TRUST<br><span>NOTHING.</span></div><p class="sub">One player has corrupted instructions. Everyone else has suspicions. Nobody has proof.</p><div class="panel"><div class="eyebrow">JOIN THE CHAOS</div><div class="field"><input id="name" maxlength="18" placeholder="Your name" autocomplete="nickname"></div><div class="field"><input id="code" maxlength="4" placeholder="ROOM CODE (optional)" style="text-transform:uppercase;letter-spacing:.2em"></div>${btn('JOIN ROOM →','join()')}${btn('CREATE ROOM','create()','alt')}<div class="error"></div></div>${btn('HOW TO PLAY →','intro=0;renderIntro()','alt')}<div class="footer">2–8 players · No accounts · Play on your phones</div>`}
const slides=[['⚡','BEAT THE CHALLENGE','Tap, guess, sort or predict the crowd. Everyone plays on their own phone.'],['👁','SPOT THE GLITCH','Someone receives corrupted instructions. Use the Suspicion Meter to decide who seems suspicious.'],['🃏','ACCUSE & MUTATE','Vote for the Glitch, earn points, and choose cards that change future rounds.']];
function renderIntro(){let s=slides[intro];app.innerHTML=`${icon()}<div class="panel center fade"><div class="eyebrow">HOW TO PLAY · ${intro+1}/3</div><div class="intrographic">${s[0]}</div><h2>${s[1]}</h2><p class="sub">${s[2]}</p>${btn(intro===2?'LET’S GO →':'NEXT →',intro===2?'render()':'intro++;renderIntro()')}</div>`}
function players(){return state.players.map(p=>`<div class="player"><span><i class="dot ${p.online?'':'off'}"></i>${esc(p.name)} ${p.id===state.host?'👑':''} ${p.spectator?'👁':''}</span><span class="score">${p.score===null?'???':p.score}</span></div>`).join('')}
function lobby(){return `${icon()}<div class="eyebrow" style="margin-top:35px">YOUR ROOM CODE</div><div class="bigcode">${esc(state.code)}</div><p class="sub center">Share this code and your website link with friends.</p>${btn('COPY INVITE','copyInvite()','alt')}<div class="panel"><div class="row"><h2>LOBBY</h2><span class="pill">${state.players.length}/8</span></div>${players()}</div>${state.me.host?`<div class="panel"><label>NUMBER OF ROUNDS</label><select onchange="api('settings',{rounds:+this.value})">${[5,7,10].map(n=>`<option value="${n}" ${state.rounds===n?'selected':''}>${n} rounds</option>`).join('')}</select>${btn('START GAME →',"act('start')",'',)}<div class="error"></div></div>`:'<p class="sub center">Waiting for host to start…</p>'}<div class="footer">75 seconds per round · 2–8 players</div>`}
function countdown(){return Math.max(0,Math.ceil((state.deadline-Date.now())/1000))}
function gameHeader(){return `${icon()}<div class="row" style="margin-top:22px"><span class="eyebrow">ROUND ${state.round} / ${state.rounds}</span><span class="pill">${state.phase.toUpperCase()}</span></div><div class="row"><span class="muted">${{ready:'Get ready for the next challenge.',challenge:'Follow the instructions and submit.',reveal:'Check the clue. Accusations are next.',vote:'Vote before the timer runs out.',mutate:'The round winner changes the rules.',finished:'The chaos has ended.'}[state.phase]}</span><span class="timer" id="timer">${countdown()}</span></div><div class="progress"><div id="bar" style="width:100%"></div></div><div class="mutations">${state.mutations.map(m=>`<span class="badge">${esc(m.toUpperCase())}</span>`).join('')}</div>`}
function challenge(){let p=state.prompt;if(!p)return '';let body='';if(p.type==='guess')body=`<input id="guess" type="number" inputmode="decimal" placeholder="Enter your guess">${btn('LOCK IN GUESS',"submitGuess()")}`;
if(p.type==='majority')body=`<div class="choices">${p.options.map((o,i)=>`<button onclick="submitValue(${JSON.stringify(o).replace(/"/g,'&quot;')})">${esc(o)}</button>`).join('')}</div>`;
if(p.type==='sort')body=`<p class="muted">${sort.length}/4 selected · tap in order</p>${p.items.filter(x=>!sort.includes(x)).map((x,i)=>`<button class="sort-item" onclick="selectSort('${esc(x)}')">${esc(x)}</button>`).join('')}<p class="sub">${sort.map(esc).join(' → ')}</p>${btn('RESET','sort=[];render()','alt')}${sort.length===4?btn('LOCK IN ORDER',"submitValue(sort)"):''}`;
if(p.type==='tap')body=`<p class="sub center">Tap on each pulse. Your timing error is measured against the beat.</p><button class="pulse" aria-label="Tap to beat" onclick="tap()"></button><p class="center">TAPS: <strong id="taps">${tapTimes.length}</strong></p>${btn('LOCK IN RHYTHM',"submitTap()")}`;
return `<div class="panel ${state.me.glitch?'pink':'lime'} fade"><div class="eyebrow">${state.me.glitch?'<span class="glitch">⚠ YOU ARE THE GLITCH</span>':'⚡ MICRO-CHALLENGE'}</div><h2>${esc(p.q)}</h2><div class="hint">${state.me.glitch?'SECRET: Your instructions have been corrupted. Complete the task and avoid suspicion.':esc(p.hint)}</div>${state.submission?'<h2 class="center">✓ LOCKED IN</h2><p class="sub center">Waiting for the phase to end…</p>':body}</div>`}
function reveal(){return `<div class="panel fade"><div class="eyebrow">RESULTS · SUSPICION METER</div><h2>WHO FELT OFF?</h2><div class="panel pink"><p>👁 ${esc(state.suspicion)}</p><p class="muted">A clue, not proof. The Glitch remains anonymous.</p></div>${state.results?.challenge.map(s=>`<div class="player"><span>${esc(s.name)}</span><span class="score">+${s.points} ${s.submitted?'':'(no entry)'}</span></div>`).join('')||''}</div>`}
function vote(){let ps=state.players.filter(x=>!x.spectator);return `<div class="panel pink fade"><div class="eyebrow">ACCUSE</div><h2>WHO IS THE GLITCH?</h2><div class="hint">${esc(state.suspicion)}</div>${state.voted?'<h2 class="center">✓ VOTE LOCKED</h2>':ps.length===2?`${btn('YES — THE OTHER PLAYER',"act('vote',{target:'yes'})",'hot')}${btn('NO — NOT THEM',"act('vote',{target:'no'})",'alt')}`:`<div class="choices">${ps.filter(x=>x.id!==state.me.id).map(p=>`<button onclick="act('vote',{target:'${p.id}'})">${esc(p.name)}</button>`).join('')}</div>`}</div>`}
function mutate(){let r=state.results;return `<div class="panel fade"><div class="eyebrow">THE TRUTH</div><h2 class="glitch">${esc(r?.glitchNames.join(' + ')||'?')} WAS THE GLITCH</h2>${r?.voteNames.map(x=>`<p>${esc(x.name)} ${x.escaped?'escaped (+100)':'was caught'} · ${x.sabotage?'sabotage +100':'no sabotage'}</p>`).join('')||''}<h3>Votes</h3>${r?.accusations.length?r.accusations.map(v=>`<p>${esc(v.name)} → ${esc(v.target)} ${v.correct?'✓ +75':'✕'}</p>`).join(''):'<p class="muted">Nobody voted.</p>'}</div><div class="panel"><div class="eyebrow">MUTATE THE GAME</div>${state.round===state.rounds?'<h2>FINAL ROUND COMPLETE</h2>':state.me.id===state.chooser?`<h2>YOU PICK THE NEXT RULE</h2>${state.offers.length?state.offers.map(c=>`<button class="sort-item" onclick="act('mutate',{card:'${c.id}'})"><strong>${esc(c.name)}</strong><br><small>${esc(c.desc)}</small></button>`).join(''):'<p>Mutation selected. Next round loading…</p>'}`:'<p>Waiting for the round winner to pick a mutation…</p>'}</div>`}
function finished(){let ps=[...state.players].filter(p=>!p.spectator).sort((a,b)=>(b.score||0)-(a.score||0)),votes=state.history.flatMap(h=>h.votes),counts=Object.fromEntries(ps.map(p=>[p.name,0]));for(let v of votes)counts[v.target]=(counts[v.target]||0)+1;let least=[...ps].sort((a,b)=>(counts[a.name]||0)-(counts[b.name]||0))[0];return `<div class="center" style="margin:40px 0"><div class="eyebrow">FINAL TRANSMISSION</div><div class="hero"><span>GAME</span><br>OVER.</div></div><div class="panel lime"><h2>🏆 FINAL LEADERBOARD</h2>${ps.map((p,i)=>`<div class="player"><span class="rank">${i+1}. ${esc(p.name)}</span><span class="score">${p.score}</span></div>`).join('')}</div><div class="panel pink"><h2>🏅 AWARDS</h2><p class="award">👁 Never Suspected: ${esc(least?.name||'Nobody')}</p><p class="award">🕵 Most Paranoid: ${esc(ps.sort((a,b)=>votes.filter(v=>v.name===b.name).length-votes.filter(v=>v.name===a.name).length)[0]?.name||'Nobody')}</p><p class="award">🎭 Best Liar: ${esc(state.history.flatMap(h=>h.glitches).sort((a,b)=>state.history.filter(h=>h.glitches.includes(b)).length-state.history.filter(h=>h.glitches.includes(a)).length)[0]||'Nobody')}</p></div>${btn('BACK TO HOME','reset()','alt')}`}
function render(){if(!state){app.innerHTML=home();return}let html=state.phase==='lobby'?lobby():gameHeader()+(state.me.spectator?'<div class="panel"><h2>👁 SPECTATOR MODE</h2><p class="sub">You joined mid-game. Watch the leaderboard and join the next game.</p></div>':state.phase==='ready'?`<div class="panel center"><h2>${state.me.glitch?'<span class="glitch">YOU ARE THE GLITCH</span>':'GET READY'}</h2><p class="sub">${state.me.glitch?'Your instructions will be secretly corrupted. Blend in.':'Someone has different instructions. Pay attention.'}</p></div>`:state.phase==='challenge'?challenge():state.phase==='reveal'?reveal():state.phase==='vote'?vote():state.phase==='mutate'?mutate():finished());if(state.phase!=='lobby'&&state.phase!=='finished')html+=`<div class="panel"><div class="eyebrow">LIVE LEADERBOARD</div>${players()}</div>`;app.innerHTML=html}
async function act(action,body){try{await api(action,body);sound();vibrate()}catch(e){error(e.message)}}function submitGuess(){let e=document.querySelector('#guess');if(e?.value!=='')act('submit',{value:Number(e.value)})}function submitValue(value){act('submit',{value})}function selectSort(x){if(!sort.includes(x))sort.push(x);render()}function tap(){let now=Date.now();tapTimes.push(now);document.querySelector('#taps').textContent=tapTimes.length;vibrate()}function submitTap(){if(!tapTimes.length)return;let errors=tapTimes.map(t=>{let n=t%1000;return Math.min(n,1000-n)});submitValue(Math.round(errors.reduce((a,b)=>a+b,0)/errors.length))}function copyInvite(){navigator.clipboard?.writeText(`${location.origin}/\nRoom: ${state.code}`).then(()=>alert('Invite copied!')).catch(()=>prompt('Copy invite:',`${location.origin}/ — Room ${state.code}`))}function reset(){events?.close();session=null;state=null;localStorage.removeItem('glitch-session');render()}
setInterval(()=>{if(session&&state){let e=document.querySelector('#timer');if(e)e.textContent=countdown();let b=document.querySelector('#bar');if(b){let lengths={ready:5,challenge:state.mutations.includes('short')?17:25,reveal:8,vote:15,mutate:22};b.style.width=Math.max(0,Math.min(100,(state.deadline-Date.now())/(lengths[state.phase]*1000)*100))+'%'}}},200);setInterval(()=>{if(session)api('ping').catch(()=>{})},6000);if(session)connect();else render();
